### PR TITLE
Parsers(rapid): Added TOML version of rapid parser

### PR DESCRIPTION
**Pull request by pipliggins**

### CODE REVIEW

**Comment by abhidg** [comment]
Looks good! Is it possible to auto-reformat some of the shorter tables inline? like values/if blocks

**Comment by ekamau** [comment]
Just looking at this. Are we indenting the toml format? looks nicer ..

**Comment by pipliggins** [comment]
> Just looking at this. Are we indenting the toml format? looks nicer ..
> […](#)

Yes - it makes some of the longer mappings much easier to read if it's indented a bit. We're still trying to work out the best way to enforce a style though!

**Comment by pipliggins** [comment]
> Looks good! Is it possible to auto-reformat some of the shorter tables inline? like values/if blocks

I don't know if there's a way to auto format that... I'll take a look/just do it by hand in this instance

**Comment by abhidg** [comment]
Thanks!

**Pull request merged**
