### PR TITLE
Make checkbox fields explicit

### PR DESCRIPTION
**Pull request by pipliggins**

### CODE REVIEW

**Review by ekamau — APPROVED** [review]
looks good!

**Comment by pipliggins** [comment]
@sadiekelly sorry to bug again... I thought this covered all the bases for checkbox fields by looking for fields with ___x in the name, but having looked again at some of the data files it's not clear to me that a lot of the symptom data wasn't also recorded as checkbox-like - e.g., the Guinea, Ghana & Uganda-v2 (these are just the first ones I checked) seem to have a data structure that suggests they use 0 as a default for admission symptoms/comorbidities, even though there are 'unknown' as options.

Any insights?

**Comment by pipliggins** [comment]
> > @sadiekelly sorry to bug again... I thought this covered all the bases for checkbox fields by looking for fields with ___x in the name, but having looked again at some of the data files it's not clear to me that a lot of the symptom data wasn't also recorded as checkbox-like - e.g., the Guinea, Ghana & Uganda-v2 (these are just the first ones I checked) seem to have a data structure that suggests they use 0 as a default for admission symptoms/comorbidities, even though there are 'unknown' as options.
> > Any insights?
> 
> hi @pipliggins for those databases you've mentioned, it is fine to treat these not as checkboxes - they were either radio button or dropdown lists for the Yes/No/Unknown options meaning that one option should be selected and if none were selected then the cell in the csv for that data item would just be blank, there would not be a default entry for these. I think your approach of identifying checkbox fields by the ___x pattern sounds sensible, this will definitely cover all redcap databases that used checkboxes. I think other database formats didn't tend to use checkboxes, it was quite a redcap thing. I can do a quick look through the data dictionaries to find non-redcap setups and look for any rogue checkboxes if that would be helpful?

Hi @sadiekelly if you have the spare capacity that would be great! The well filled-in radio fields make spotting these easily a bit more difficult, good to know.

**Comment by sadiekelly** [comment]
> > > @sadiekelly sorry to bug again... I thought this covered all the bases for checkbox fields by looking for fields with ___x in the name, but having looked again at some of the data files it's not clear to me that a lot of the symptom data wasn't also recorded as checkbox-like - e.g., the Guinea, Ghana & Uganda-v2 (these are just the first ones I checked) seem to have a data structure that suggests they use 0 as a default for admission symptoms/comorbidities, even though there are 'unknown' as options.
> > > Any insights?
> > 
> > 
> > hi @pipliggins for those databases you've mentioned, it is fine to treat these not as checkboxes - they were either radio button or dropdown lists for the Yes/No/Unknown options meaning that one option should be selected and if none were selected then the cell in the csv for that data item would just be blank, there would not be a default entry for these. I think your approach of identifying checkbox fields by the ___x pattern sounds sensible, this will definitely cover all redcap databases that used checkboxes. I think other database formats didn't tend to use checkboxes, it was quite a redcap thing. I can do a quick look through the data dictionaries to find non-redcap setups and look for any rogue checkboxes if that would be helpful?
> 
> Hi @sadiekelly if you have the spare capacity that would be great! The well filled-in radio fields make spotting these easily a bit more difficult, good to know.

hi @pipliggins I've checked through the data dictionaries, most are REDCap format so will be covered by the ___x. Of the couple that are not, generally checkboxes were not used. I think predicovid may have been one, and the checkbox fields there are not mapped so no changes needed. Otherwise looks like the checkboxes have been accounted for so all good!

**Comment by pipliggins** [comment]
> > > > @sadiekelly sorry to bug again... I thought this covered all the bases for checkbox fields by looking for fields with ___x in the name, but having looked again at some of the data files it's not clear to me that a lot of the symptom data wasn't also recorded as checkbox-like - e.g., the Guinea, Ghana & Uganda-v2 (these are just the first ones I checked) seem to have a data structure that suggests they use 0 as a default for admission symptoms/comorbidities, even though there are 'unknown' as options.
> > > > Any insights?
> > > 
> > > 
> > > hi @pipliggins for those databases you've mentioned, it is fine to treat these not as checkboxes - they were either radio button or dropdown lists for the Yes/No/Unknown options meaning that one option should be selected and if none were selected then the cell in the csv for that data item would just be blank, there would not be a default entry for these. I think your approach of identifying checkbox fields by the ___x pattern sounds sensible, this will definitely cover all redcap databases that used checkboxes. I think other database formats didn't tend to use checkboxes, it was quite a redcap thing. I can do a quick look through the data dictionaries to find non-redcap setups and look for any rogue checkboxes if that would be helpful?
> > 
> > 
> > Hi @sadiekelly if you have the spare capacity that would be great! The well filled-in radio fields make spotting these easily a bit more difficult, good to know.
> 
> hi @pipliggins I've checked through the data dictionaries, most are REDCap format so will be covered by the ___x. Of the couple that are not, generally checkboxes were not used. I think predicovid may have been one, and the checkbox fields there are not mapped so no changes needed. Otherwise looks like the checkboxes have been accounted for so all good!

Fab, thanks for checking this @sadiekelly!

**Pull request merged**
